import type { EmployeeProfile } from "@/types/talent";

export const mockEmployees: EmployeeProfile[] = [
  {
    id: "emp-001",
    employeeCode: "TM-1001",
    photoUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
    fullName: "佐藤 美咲",
    fullNameKana: "サトウ ミサキ",
    email: "misaki.sato@example.com",
    department: "プロダクト開発部",
    position: "プロダクトマネージャー",
    grade: "G4",
    location: "東京本社",
    joinedOn: "2020-04-01",
    managerId: "mgr-001",
    managerName: "高橋 健",
    skills: ["プロダクト戦略", "SQL", "UXリサーチ", "アジャイル"],
    strengths: ["課題構造化", "合意形成", "顧客理解"],
    developmentAreas: ["事業計画", "財務理解", "組織マネジメント"],
    latestRating: "A",
    nextInterviewOn: "2026-06-12",
    careerStage: "リード候補",
    aiSummary:
      "プロダクト視点と顧客理解が強く、次の成長テーマは事業計画と組織マネジメントです。",
    oneOnOneReadiness: 82,
    engagement: 78,
    growthVelocity: 86,
    riskLevel: "low",
    focusTheme: "事業責任者に向けた視座拡張",
    recommendedAction: "次回面談では事業計画ドラフトへのフィードバックを中心に扱う",
    phone: "03-0000-1001",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "プロダクトマネージャー",
        startedOn: "2023-04-01",
        summary: "新規SaaSプロダクトのロードマップ策定とKPI設計を担当。",
        skills: ["ロードマップ", "KPI設計", "顧客インタビュー"],
      },
      {
        company: "自社",
        title: "フロントエンドエンジニア",
        startedOn: "2020-04-01",
        endedOn: "2023-03-31",
        summary: "React/TypeScriptで管理画面の開発を担当。",
        skills: ["React", "TypeScript", "アクセシビリティ"],
      },
    ],
    certifications: [
      {
        name: "認定スクラムプロダクトオーナー",
        issuer: "Scrum Alliance",
        acquiredOn: "2024-08-10",
        status: "active",
      },
      {
        name: "応用情報技術者",
        issuer: "IPA",
        acquiredOn: "2021-12-20",
        status: "active",
      },
    ],
    performanceReviews: [
      {
        period: "2025 H2",
        rating: "A",
        score: 4.4,
        reviewer: "高橋 健",
        summary: "顧客課題の構造化と開発チームとの合意形成に強み。次期は事業計画への接続を強化。",
        salaryBand: "7.2M-8.0M",
        isSensitive: true,
      },
      {
        period: "2025 H1",
        rating: "B+",
        score: 3.8,
        reviewer: "高橋 健",
        summary: "既存機能改善で解約率低下に貢献。",
        salaryBand: "6.8M-7.4M",
        isSensitive: true,
      },
    ],
    interviews: [
      {
        heldOn: "2026-04-18",
        interviewer: "高橋 健",
        topic: "半期キャリア面談",
        memo: "事業責任者に近い役割への挑戦意欲が高い。財務理解の強化が課題。",
        actionItems: ["PL基礎研修を受講", "次回までに事業計画ドラフトを作成"],
        aiSummary: {
          summary: "事業責任者への志向が明確。財務理解と組織マネジメント経験を補うことで次段階に進みやすい。",
          sentiment: "positive",
          keyTopics: ["事業責任", "財務理解", "組織マネジメント"],
          concerns: ["PL理解の実務経験が少ない"],
          nextQuestions: ["事業計画で最も不確実だと感じる前提は何か"],
          actionItems: [
            { title: "PL基礎研修を受講", owner: "佐藤 美咲", dueHint: "次回面談まで" },
          ],
          riskSignals: [],
        },
      },
    ],
    careerPreference: {
      desiredRole: "事業開発責任者",
      desiredDepartment: "新規事業開発部",
      mobility: "国内転勤可",
      skillsToDevelop: ["事業計画", "ファイナンス", "組織マネジメント"],
      notes: "中長期ではプロダクトと事業の両方を見られるポジションを希望。",
    },
    goals: [
      {
        title: "事業計画ドラフト作成",
        progress: 70,
        dueOn: "2026-06-30",
        owner: "佐藤 美咲",
      },
      {
        title: "PL基礎研修の修了",
        progress: 35,
        dueOn: "2026-07-15",
        owner: "高橋 健",
      },
    ],
  },
  {
    id: "emp-002",
    employeeCode: "TM-1034",
    photoUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=320&q=80",
    fullName: "山本 蓮",
    fullNameKana: "ヤマモト レン",
    email: "ren.yamamoto@example.com",
    department: "データ戦略部",
    position: "データサイエンティスト",
    grade: "G3",
    location: "大阪オフィス",
    joinedOn: "2022-10-01",
    managerId: "mgr-001",
    managerName: "高橋 健",
    skills: ["Python", "機械学習", "dbt", "統計分析"],
    strengths: ["分析設計", "モデル改善", "データ可視化"],
    developmentAreas: ["説明責任", "関係部署展開", "優先度設計"],
    latestRating: "B+",
    nextInterviewOn: "2026-05-28",
    careerStage: "専門性伸長",
    aiSummary:
      "分析力とモデル改善に強みがあります。事業部との接続を増やすとリード職への移行が見えます。",
    oneOnOneReadiness: 91,
    engagement: 62,
    growthVelocity: 74,
    riskLevel: "medium",
    focusTheme: "分析成果を事業意思決定へ接続",
    recommendedAction: "面談で営業企画との関係性と本人の負荷感を確認する",
    phone: "06-0000-1034",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "データサイエンティスト",
        startedOn: "2022-10-01",
        summary: "需要予測モデルと営業ダッシュボードを開発。",
        skills: ["Python", "BigQuery", "需要予測"],
      },
    ],
    certifications: [
      {
        name: "Google Professional Data Engineer",
        issuer: "Google Cloud",
        acquiredOn: "2024-05-14",
        expiresOn: "2026-05-14",
        status: "expiring",
      },
    ],
    performanceReviews: [
      {
        period: "2025 H2",
        rating: "B+",
        score: 3.7,
        reviewer: "高橋 健",
        summary: "モデル改善により予測精度を改善。説明責任と関係部署への展開が次のテーマ。",
        salaryBand: "6.0M-6.8M",
        isSensitive: true,
      },
    ],
    interviews: [
      {
        heldOn: "2026-03-30",
        interviewer: "高橋 健",
        topic: "1on1",
        memo: "ML基盤よりも事業部に近い分析支援への関心が高い。",
        actionItems: ["営業企画との週次定例に参加", "分析テーマの優先度表を作る"],
        aiSummary: {
          summary: "事業部に近い分析支援への関心が高い。現場接点を増やす一方で優先度設計の支援が必要。",
          sentiment: "neutral",
          keyTopics: ["分析支援", "営業企画", "優先度設計"],
          concerns: ["依頼増による負荷上昇"],
          nextQuestions: ["今の分析依頼で最も意思決定に効いているものは何か"],
          actionItems: [
            { title: "分析テーマの優先度表を作る", owner: "山本 蓮", dueHint: "2週間以内" },
          ],
          riskSignals: ["関係部署からの依頼増加"],
        },
      },
    ],
    careerPreference: {
      desiredRole: "アナリティクスリード",
      desiredDepartment: "データ戦略部",
      mobility: "転勤不可",
      skillsToDevelop: ["データプロダクト設計", "ステークホルダー管理"],
      notes: "現場に近い課題設定と意思決定支援に軸足を置きたい。",
    },
    goals: [
      {
        title: "営業企画向け分析テーマ整理",
        progress: 55,
        dueOn: "2026-06-14",
        owner: "山本 蓮",
      },
      {
        title: "分析結果説明テンプレート作成",
        progress: 25,
        dueOn: "2026-07-01",
        owner: "高橋 健",
      },
    ],
  },
  {
    id: "emp-003",
    employeeCode: "TM-1088",
    photoUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=320&q=80",
    fullName: "田中 葵",
    fullNameKana: "タナカ アオイ",
    email: "aoi.tanaka@example.com",
    department: "人事企画部",
    position: "HRビジネスパートナー",
    grade: "G4",
    location: "東京本社",
    joinedOn: "2019-07-01",
    managerId: "mgr-002",
    managerName: "中村 優子",
    skills: ["組織開発", "労務", "人材配置", "コーチング"],
    strengths: ["制度運用", "組織課題把握", "コーチング"],
    developmentAreas: ["報酬設計", "ピープルアナリティクス", "全社展開"],
    latestRating: "A-",
    nextInterviewOn: "2026-06-05",
    careerStage: "次世代責任者候補",
    aiSummary:
      "組織開発と評価運用の経験が厚く、人事制度責任者に向けて報酬設計の実務機会が有効です。",
    oneOnOneReadiness: 68,
    engagement: 84,
    growthVelocity: 79,
    riskLevel: "low",
    focusTheme: "人事制度責任者への実務接続",
    recommendedAction: "報酬制度プロジェクトで任せる範囲を明確にする",
    phone: "03-0000-1088",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "HRビジネスパートナー",
        startedOn: "2021-04-01",
        summary: "開発組織の人員計画、評価運用、サクセッション計画を担当。",
        skills: ["組織設計", "評価制度", "人員計画"],
      },
      {
        company: "自社",
        title: "採用担当",
        startedOn: "2019-07-01",
        endedOn: "2021-03-31",
        summary: "中途採用の母集団形成と候補者体験改善を担当。",
        skills: ["採用広報", "面接設計"],
      },
    ],
    certifications: [
      {
        name: "キャリアコンサルタント",
        issuer: "厚生労働省",
        acquiredOn: "2022-09-01",
        status: "active",
      },
    ],
    performanceReviews: [
      {
        period: "2025 H2",
        rating: "A-",
        score: 4.1,
        reviewer: "中村 優子",
        summary: "主要部門の離職率改善と後継者候補整理を主導。",
        salaryBand: "7.0M-7.8M",
        isSensitive: true,
      },
    ],
    interviews: [
      {
        heldOn: "2026-04-04",
        interviewer: "中村 優子",
        topic: "キャリア面談",
        memo: "将来的には人事制度設計の責任者を希望。",
        actionItems: ["報酬制度プロジェクトに参画", "外部制度事例を調査"],
        aiSummary: {
          summary: "人事制度責任者への志向が明確。制度事例調査から報酬制度プロジェクトの実務へ接続するのが有効。",
          sentiment: "positive",
          keyTopics: ["報酬制度", "制度設計", "責任者志向"],
          concerns: ["全社展開時のデータ活用経験"],
          nextQuestions: ["制度設計で最も改善したい社員体験は何か"],
          actionItems: [
            { title: "外部制度事例を調査", owner: "田中 葵", dueHint: "今月末" },
          ],
          riskSignals: [],
        },
      },
    ],
    careerPreference: {
      desiredRole: "人事制度責任者",
      desiredDepartment: "人事企画部",
      mobility: "国内転勤可",
      skillsToDevelop: ["報酬設計", "ピープルアナリティクス"],
      notes: "採用・組織開発の経験を制度設計に接続したい。",
    },
    goals: [
      {
        title: "報酬制度プロジェクト参画",
        progress: 45,
        dueOn: "2026-08-31",
        owner: "田中 葵",
      },
      {
        title: "制度事例レポート作成",
        progress: 80,
        dueOn: "2026-05-31",
        owner: "中村 優子",
      },
    ],
  },
  {
    id: "emp-004",
    employeeCode: "TM-1120",
    photoUrl: "",
    fullName: "伊藤 陽菜",
    fullNameKana: "イトウ ハルナ",
    email: "haruna.ito@example.com",
    department: "カスタマーサクセス部",
    position: "オンボーディングスペシャリスト",
    grade: "G3",
    location: "福岡オフィス",
    joinedOn: "2021-11-01",
    managerId: "mgr-003",
    managerName: "森田 直人",
    skills: ["オンボーディング", "顧客折衝", "ナレッジ整備"],
    strengths: ["顧客理解", "問い合わせ整理", "導入支援"],
    developmentAreas: ["データ活用", "プロセス設計"],
    latestRating: "B+",
    nextInterviewOn: "2026-06-20",
    careerStage: "専門性伸長",
    aiSummary: "導入支援と顧客理解に強みがあります。",
    oneOnOneReadiness: 76,
    engagement: 81,
    growthVelocity: 72,
    riskLevel: "low",
    focusTheme: "導入体験の標準化",
    recommendedAction: "導入時のつまずきパターンを整理する",
    phone: "092-0000-1120",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "オンボーディングスペシャリスト",
        startedOn: "2023-04-01",
        summary: "新規顧客の導入支援と活用定着の伴走を担当。",
        skills: ["オンボーディング", "顧客折衝"],
      },
      {
        company: "自社",
        title: "サポート担当",
        startedOn: "2021-11-01",
        endedOn: "2023-03-31",
        summary: "問い合わせ対応とヘルプページ改善を担当。",
        skills: ["FAQ整備", "問い合わせ分析"],
      },
    ],
    certifications: [
      {
        name: "ITパスポート",
        issuer: "IPA",
        acquiredOn: "2022-03-15",
        status: "active",
      },
    ],
    performanceReviews: [],
    interviews: [],
    careerPreference: {
      desiredRole: "カスタマーサクセス企画",
      desiredDepartment: "カスタマーサクセス部",
      mobility: "転勤不可",
      skillsToDevelop: ["データ分析", "業務設計"],
      notes: "導入支援で得た知見を仕組み化する役割に挑戦したい。",
    },
    goals: [],
  },
  {
    id: "emp-005",
    employeeCode: "TM-1156",
    photoUrl:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=320&q=80",
    fullName: "小林 直樹",
    fullNameKana: "コバヤシ ナオキ",
    email: "naoki.kobayashi@example.com",
    department: "セールス企画部",
    position: "セールスオペレーション",
    grade: "G4",
    location: "東京本社",
    joinedOn: "2018-05-01",
    managerId: "mgr-004",
    managerName: "西村 拓也",
    skills: ["Salesforce", "業務設計", "KPI設計"],
    strengths: ["営業プロセス改善", "ダッシュボード設計", "部門間調整"],
    developmentAreas: ["採用育成", "マネジメント"],
    latestRating: "A-",
    nextInterviewOn: "2026-06-18",
    careerStage: "リード候補",
    aiSummary: "営業活動の可視化と業務設計に強みがあります。",
    oneOnOneReadiness: 73,
    engagement: 79,
    growthVelocity: 78,
    riskLevel: "low",
    focusTheme: "営業プロセスの再設計",
    recommendedAction: "営業企画の標準指標を整理する",
    phone: "03-0000-1156",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "セールスオペレーション",
        startedOn: "2022-01-01",
        summary: "営業KPI、商談管理、Salesforce運用を担当。",
        skills: ["Salesforce", "KPI設計"],
      },
    ],
    certifications: [
      {
        name: "Salesforce認定アドミニストレーター",
        issuer: "Salesforce",
        acquiredOn: "2023-10-10",
        status: "active",
      },
    ],
    performanceReviews: [],
    interviews: [],
    careerPreference: {
      desiredRole: "レベニューオペレーションリード",
      desiredDepartment: "セールス企画部",
      mobility: "国内転勤可",
      skillsToDevelop: ["マネジメント", "事業計画"],
      notes: "営業、CS、マーケティングを横断した業務設計に関わりたい。",
    },
    goals: [],
  },
  {
    id: "emp-006",
    employeeCode: "TM-1181",
    photoUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=320&q=80",
    fullName: "鈴木 玲奈",
    fullNameKana: "スズキ レナ",
    email: "rena.suzuki@example.com",
    department: "デザイン部",
    position: "UXデザイナー",
    grade: "G3",
    location: "東京本社",
    joinedOn: "2023-02-01",
    managerId: "mgr-005",
    managerName: "青木 真理",
    skills: ["ユーザー調査", "プロトタイピング", "Figma"],
    strengths: ["ユーザー調査", "情報設計", "プロトタイピング"],
    developmentAreas: ["定量分析", "ファシリテーション"],
    latestRating: "B",
    nextInterviewOn: "2026-06-25",
    careerStage: "専門性伸長",
    aiSummary: "ユーザー調査と体験設計に強みがあります。",
    oneOnOneReadiness: 69,
    engagement: 75,
    growthVelocity: 77,
    riskLevel: "low",
    focusTheme: "調査結果を開発意思決定につなげる",
    recommendedAction: "調査計画と検証指標を整理する",
    phone: "03-0000-1181",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "UXデザイナー",
        startedOn: "2023-02-01",
        summary: "新機能のユーザー調査、画面設計、プロトタイプ作成を担当。",
        skills: ["Figma", "ユーザーインタビュー"],
      },
    ],
    certifications: [],
    performanceReviews: [],
    interviews: [],
    careerPreference: {
      desiredRole: "プロダクトデザイナー",
      desiredDepartment: "デザイン部",
      mobility: "転勤不可",
      skillsToDevelop: ["定量分析", "プロダクト戦略"],
      notes: "調査から施策化まで一貫して関われるデザイナーを目指したい。",
    },
    goals: [],
  },
  {
    id: "emp-007",
    employeeCode: "TM-1214",
    photoUrl: "",
    fullName: "森 大輔",
    fullNameKana: "モリ ダイスケ",
    email: "daisuke.mori@example.com",
    department: "情報システム部",
    position: "コーポレートエンジニア",
    grade: "G4",
    location: "名古屋オフィス",
    joinedOn: "2020-09-01",
    managerId: "mgr-006",
    managerName: "北川 誠",
    skills: ["SaaS管理", "セキュリティ", "自動化"],
    strengths: ["SaaS運用", "セキュリティ設計", "業務自動化"],
    developmentAreas: ["全社展開", "ドキュメンテーション"],
    latestRating: "A",
    nextInterviewOn: "2026-07-02",
    careerStage: "リード候補",
    aiSummary: "社内システム運用とセキュリティ設計に強みがあります。",
    oneOnOneReadiness: 70,
    engagement: 83,
    growthVelocity: 80,
    riskLevel: "low",
    focusTheme: "社内SaaS運用の標準化",
    recommendedAction: "運用ルールの公開範囲を整理する",
    phone: "052-0000-1214",
    employmentStatus: "active",
    careerHistories: [
      {
        company: "自社",
        title: "コーポレートエンジニア",
        startedOn: "2020-09-01",
        summary: "社内SaaS、アカウント管理、自動化スクリプトの整備を担当。",
        skills: ["SaaS管理", "自動化", "セキュリティ"],
      },
    ],
    certifications: [
      {
        name: "情報処理安全確保支援士",
        issuer: "IPA",
        acquiredOn: "2024-04-01",
        status: "active",
      },
    ],
    performanceReviews: [],
    interviews: [],
    careerPreference: {
      desiredRole: "社内IT基盤リード",
      desiredDepartment: "情報システム部",
      mobility: "国内転勤可",
      skillsToDevelop: ["全社展開", "プロジェクト設計"],
      notes: "安全で使いやすい社内IT基盤づくりに関わりたい。",
    },
    goals: [],
  },
];
